# -*- coding: utf-8 -*-
"""change_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ySPCWi41riqwLM26WpyWBG6_KeelOew
"""

import glob
import cv2 as cv
import os,shutil
import numpy as np
from datetime import datetime
import csv
# from skimage.metrics import structural_similarity as ssim
import scipy.io as scio
# from summe import evaluate_summary
import numba as nb

import multiprocessing
from skimage.metrics import structural_similarity as ssim
import skimage.metrics as metrics

from numba import njit, cuda


MAX_THRES = 0.9
MIN_THRES = 0.5

adapt_thrs_arry = []

every = 5
nFPS = 25
nFrames = 1000
adapt_thrs_ar_x = []
missing_frames_lst = []
procsd_frms_lst = []
summ_vect = []

base_fldr = 'D:/Project/DataSets/SumMe/'
GTPATH = os.path.join(base_fldr, 'GT/')
VIDEOPATH = os.path.join(base_fldr, 'videos/')
inp_fldr = VIDEOPATH
csv_path = os.path.join(inp_fldr, 'record_summe_17_Optc_f1scr.csv')
file = open(csv_path, 'w', newline='')
writer = csv.writer(file, quoting=csv.QUOTE_NONNUMERIC)


def finegrain_saliencmap(image):
    threshMap = None
    # (success, saliencyMap) = saliency.computeSaliency(image)
    # threshMap = cv.threshold((saliencyMap*255).astype("uint8"), 0, 255,
    #                           cv.THRESH_BINARY | cv.THRESH_OTSU)[1]
    # saliencyMap = (saliencyMap*255).astype("uint8")
    # show the images
    # cv.imshow("Image", image)
    # cv.imshow("Output", saliencyMap)
    # cv.imshow("Thresh", threshMap)
    # cv.waitKey(0)

    return threshMap

def objectness_saliency(img):
#     saliency = cv.saliency.ObjectnessBING_create()
#     saliency.setTrainingPath("F:\\Jyothi\\OpenCV\\objectness_models")
#     # compute the bounding box predictions used to indicate saliency
#     (success, saliencyMap) = saliency.computeSaliency(img)
#     numDetections = saliencyMap.shape[0]
#     for i in range(0, min(numDetections, 20)):
#         # extract the bounding box coordinates
#         (startX, startY, endX, endY) = saliencyMap[i].flatten()
#
#         # randomly generate a color for the object and draw it on the image
#         output = img.copy()
#         color = np.random.randint(0, 255, size=(3,))
#         color = [int(c) for c in color]
#         cv.rectangle(img, (startX, startY), (endX, endY), color, 2)
#         # show the output image
#     cv.imshow("Image", img)
#     cv.waitKey(0)
    pass

def orig_frames(inp_vid,opt_frms):
    cap = cv.VideoCapture(inp_vid)
    cnt = 0
    res, frame = cap.read()
    opt_frm = os.path.join(opt_frms, 'frame')
    while res:
        opt_pth = opt_frm + str(cnt) + '.jpg'
        cv.imwrite(opt_pth, frame)
        cnt += 1
        res, frame = cap.read()
    return cnt - 1

@njit(fastmath=True)
def ssim_lite(x, y):
    mu_x = x.mean()
    mu_y = y.mean()
    #variance for adjacent frames x and y are calculated
    #co-variance for x and y is calculated
    var_x = ((x - mu_x) ** 2).mean()
    var_y = ((y - mu_y) ** 2).mean()
    cov_xy = ((x - mu_x) * (y - mu_y)).mean()
# from actual SSIM K1 = 0.01, K2 = 0.03, default sigma for Gaussian is 1.5,
    #C1, C2 are two constants with C1 = 650.25, C2 = 1950.75
    C1 = 0.01 * 255 * 255
    C2 = 0.03 * 255 * 255
    # similarity is calculated
    numer = ((2 * mu_x * mu_y + C1) * (2 * cov_xy + C2))
    denom = ((mu_x**2 + mu_y**2 + C1) * (var_x + var_y + C2))
    return  numer/ denom


@njit(parallel=True, fastmath=True)
# @njit(parallel=True, fastmath=True)
def ssim_numba(img1, img2):
    C1 = 6.5025
    C2 = 58.5225

    mu1 = np.mean(img1)
    mu2 = np.mean(img2)

    sigma1 = np.var(img1)
    sigma2 = np.var(img2)
    sigma12 = np.mean((img1 - mu1) * (img2 - mu2))

    numerator = (2*mu1*mu2 + C1) * (2*sigma12 + C2)
    denominator = (mu1**2 + mu2**2 + C1) * (sigma1 + sigma2 + C2)

    return numerator / denominator


# @nb.vectorize#("(string,string)",target='parallel')
# @nb.njit
# @nb.njit
# @nb.jit(nopython=True,nogil=True,parallel=True,fastmath=True)
def ssim_frames(inp_vid,opt_frms): #,opt_sal_frm):
    min_adpt = max_adpt = MAX_THRES
    len_thrshold = nFPS*every
    ssim_score_aary = np.zeros(len_thrshold)
    indx = 0
    # global adapt_thrs_arry
    nFlg = 1
    cap = cv.VideoCapture(inp_vid)
    tot_cnt = miss_cnt = 0
    res, frame = cap.read() #Reading first frame of the video capture object of cv2
    # opt_frm = os.path.join(opt_frms, 'frame')
    # opt_pth = opt_frm + str(tot_cnt) + '.jpg'
    # opt_sal_frm = os.path.join(opt_sal_frm,'frame')
    prev = frame
    prev_gray = cv.cvtColor(prev,cv.COLOR_BGR2GRAY)
    # cv.imwrite(opt_pth, prev)
    summ_vect.append(1)
    res, frame = cap.read() #Reading second frame of the video capture object of cv2
    tot_cnt += 1
    curr = frame
    curr_gray = cv.cvtColor(curr, cv.COLOR_BGR2GRAY)
    # sim_score = metrics.structural_similarity(prev_gray, curr_gray)
    sim_score = ssim_numba(prev_gray, curr_gray)
    prev = curr
    prev_gray = curr_gray
    adapt_threshold = sim_score
    summ_vect.append(0)
    ssim_score_aary[indx] = sim_score
    indx += 1
    adapt_thrs_arry.append(np.round(adapt_threshold,2))#round 2 decimals
    adapt_thrs_ar_x.append(tot_cnt)
    res, frame = cap.read() # 3 frame for loop continuity

    while res is True:
        tot_cnt += 1
        curr = frame
        curr_gray = cv.cvtColor(curr, cv.COLOR_BGR2GRAY)
        # sim_score = ssim(prev_gray, curr_gray)
        # sim_score = metrics.structural_similarity(prev_gray, curr_gray)
        sim_score = ssim_numba(prev_gray, curr_gray)

        # frm_score = f'frame{tot_cnt}.jpg:{sim_score}'
        ssim_score_aary[indx] = sim_score
        # print(frm_score)
        indx += 1
        if tot_cnt%len_thrshold == 0 or tot_cnt == (nFrames-1):#if (nFrames - tot_cnt) < len_thrshold
            # mean_threshold = round(np.mean(ssim_score_aary),2)
            max_ths = np.max(ssim_score_aary)
            adapt_threshold = np.round(max_ths,2)

            if adapt_threshold < MIN_THRES:
                adapt_threshold = MIN_THRES
            elif adapt_threshold > MAX_THRES:
                mean_threshold = np.round(np.mean(ssim_score_aary),2)

                if mean_threshold > MAX_THRES:
                    adapt_threshold = MAX_THRES
                elif mean_threshold < MIN_THRES:
                    adapt_threshold = MIN_THRES
                else:
                    adapt_threshold = mean_threshold
            adapt_thrs_arry.append(adapt_threshold)
            # adapt_thrs_arry.append(mean_threshold)
            adapt_thrs_ar_x.append(tot_cnt+1)
            indx = 0
            ssim_score_aary = np.zeros(len_thrshold)
        # elif tot_cnt == nFrames-1:
        #     adapt_threshold = np.round(np.max(ssim_score_aary), 2)#apply above conditions
        #     adapt_thrs_arry.append(adapt_threshold)
        #     adapt_thrs_ar_x.append(tot_cnt+1)

        if sim_score<=adapt_threshold:
            prev = curr
            prev_gray = curr_gray
            # procsd_frms_lst.append(frm_score)
            # opt_pth = opt_frm + str(tot_cnt) + '.jpg'
            # cv.imwrite(opt_pth,prev)
            summ_vect.append(1)
        else:
            # missing_frames_lst.append(frm_score)
            miss_cnt += 1
            summ_vect.append(0)
        res, frame = cap.read()
    cap.release()
    return miss_cnt#, missing_frames_lst, procsd_frms_lst#, summ_vect, min_adpt, max_adpt

def cosine_sim_frames(inp_vid,opt_frms):
    missing_frames_lst = []
    cap = cv.VideoCapture(inp_vid)
    cnt = 0
    res, frame = cap.read()
    opt_frm = os.path.join(opt_frms, 'frame')
    opt_pth = opt_frm + str(cnt) + '.jpg'

    prev = frame
    prev_gray = cv.cvtColor(prev,cv.COLOR_BGR2GRAY)
    # cv.imwrite(opt_pth, prev)
    res, frame = cap.read()
    while res:
        cnt += 1
        curr = frame
        curr_gray = cv.cvtColor(curr, cv.COLOR_BGR2GRAY)
        sim_score = ssim(prev_gray, curr_gray)
        if sim_score<0.7:
            prev = curr.copy()
            prev_gray = curr_gray.copy()
            # opt_pth = opt_frm + str(cnt) + '.jpg'
            # cv.imwrite(opt_pth,prev)
        else:
            frm_score = f'frame{cnt} .jpg:{sim_score}'
            missing_frames_lst.append(frm_score)
        res, frame = cap.read()
    cap.release()
    return cnt - len(missing_frames_lst)- 1, missing_frames_lst


def optc_flw_frames(inp_vid,opt_frms):
    missing_frames = []
    lk_params = dict(winSize=(50, 50),
                     maxLevel=2,
                     criteria=(cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 0.03))
    cap = cv.VideoCapture(inp_vid)
    cnt = 0
    ret, frame = cap.read()
    # Take first frame and find corners in it
    if not ret:
        exit()
    color = np.random.randint(0, 255, (100, 3))
    # Create a mask image for drawing purposes
    mask = np.zeros_like(frame)
    frame_count = 0
    # Threshold for optical flow magnitude to consider a frame important
    flow_threshold = 2#5

    opt_frm = os.path.join(opt_frms, 'frame')
    opt_pth = opt_frm + str(cnt) + '.jpg'
    prev = frame
    prev_gray = cv.cvtColor(prev,cv.COLOR_BGR2GRAY)
    p0 = cv.goodFeaturesToTrack(prev_gray, maxCorners=100, qualityLevel=0.3, minDistance=7, blockSize=7)
    summ_vect.append(1)
    # cv.imwrite(opt_pth, prev)

    while True:
        ret, frame = cap.read()
        cnt += 1
        if not ret:
            break
        gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        if p0 is not None:
            p1, st, err = cv.calcOpticalFlowPyrLK(prev_gray, gray, p0, None, **lk_params)
            if st.max() != 0:
                good_new = p1[st == 1]
                good_old = p0[st == 1]
                flow_magnitudes = np.sqrt(np.sum((good_new - good_old)**2, axis=1))
                mean_flw_magn = np.mean(flow_magnitudes)
                if mean_flw_magn > flow_threshold:
                    for i, (new, old) in enumerate(zip(good_new, good_old)):
                        a, b = new.ravel()
                        c, d = old.ravel()
                        mask = cv.line(mask, (int(a), int(b)), (int(c), int(d)), color[i].tolist(), 2)
                        frame = cv.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)
                    img = cv.add(frame, mask)
                    summ_vect.append(1)
                else:
                    missing_frames.append(f'frame{cnt}.jpg:{mean_flw_magn}')
                    summ_vect.append(0)

            else:
                missing_frames.append(f'frame{cnt}.jpg:{mean_flw_magn}')
                summ_vect.append(0)

        prev_gray = gray.copy()
        #p0 = p1
        if p0 is None:
            p0 = cv.goodFeaturesToTrack(prev_gray, maxCorners=100, qualityLevel=0.3, minDistance=7, blockSize=7)
        else:
            p0 = p1
    return len(missing_frames)

def video_to_frames(inp_vid,opt_fldr,option):
    frm_cnt = 0
    diff_lst = []
    summry_vect = []
    options_lst = ["","ssim","cos_sim","","","","optc_flw","orig"]
    opt_pth = os.path.join(opt_fldr, options_lst[option] + inp_file[:-4])
    # opt_salnc_fldr = os.path.join(opt_fldr,'saliency'+inp_file[:-4])
    print(opt_pth)
    miss_frm_cnt = 0
    # if os.path.exists(opt_pth) is True:
    #     shutil.rmtree(opt_pth)  # Delete folder and contents
    # os.makedirs(opt_pth)
    if option == 1:
        # miss_frm_cnt, diff_lst, prcsd_lst, summry_vect, mn, mx = ssim_frames(inp_vid, opt_pth) #,opt_salnc_fldr)
        miss_frm_cnt = ssim_frames(inp_vid, opt_pth)
    elif option == 2:
        frm_cnt, diff_lst = cosine_sim_frames(inp_vid, opt_pth)
    elif option == 6:
        miss_frm_cnt = optc_flw_frames(inp_vid, opt_pth)
    elif option == 7:
        frm_cnt, diff_lst = orig_frames(inp_vid, opt_pth)

    # return miss_frm_cnt,diff_lst, prcsd_lst, opt_pth, summry_vect,mn, mx
    return miss_frm_cnt, opt_pth

#Edge-optimized SSIM (what you should use)
# For frame selection, you only need relative similarity, not perceptual fidelity.

# Recommended “SSIM-lite” formulation
# Use global luminance + contrast + structure, no Gaussian window:

# @nb.jit(cache=True)
def record_log_data(csv_path,inp_vid,actual_frm_cnt,missing_frame_cnt,accr_arr, acc,gt_acc,mn_fscr,mx_fscr,ptime):
  # with open(csv_path, 'a', newline='', quoting=csv.QUOTE_NONNUMERIC) as file:
  #     writer = csv.writer(file)

      mn_fscr = float(f"{mn_fscr:.6f}")
      mx_fscr = float(f"{mx_fscr:.6f}")
      acc = float(f"{acc:.6f}")
      gt_acc = float(f"{gt_acc:.6f}")
      writer.writerow([inp_vid,actual_frm_cnt,missing_frame_cnt, acc, gt_acc, mn_fscr, mx_fscr,ptime])

import matplotlib.pyplot as plt

def plot_adpt_thrs(video_name):
    x = adapt_thrs_ar_x
    y = adapt_thrs_arry
    plt.xlabel('Number of Frames')
    plt.ylabel('Adapt Threshold')
    plt.plot(x,y,label=video_name, marker='o')
    plt.legend()
    # plt.show()
    plt.savefig(video_name+'.png')
from sklearn import metrics

def evaluate_summary(summary_selection, user_score,ground_score):
    '''Evaluates a summary for video videoName (where HOMEDATA points to the ground truth file)
    f_measure is the mean pairwise f-measure used in Gygli et al. ECCV 2013
    NOTE: This is only a minimal version of the matlab script'''
    nFrames = user_score.shape[0];
    nbOfUsers = user_score.shape[1];
    vect_len = nFrames
    # Check inputs
    if len(summary_selection) < nFrames:
        # warnings.warn('Pad selection with %d zeros!' % (nFrames - len(summary_selection)))
        summary_selection.extend(np.zeros(nFrames - len(summary_selection)))

    elif len(summary_selection) > nFrames:
        # warnings.warn('Crop selection (%d frames) to GT length' % (len(summary_selection) - nFrames))
        summary_selection = summary_selection[0:nFrames]

    summary_selection = summary_selection[0:nFrames]
    sum_ind = summary_selection.copy()
    user_acc = np.zeros((nbOfUsers, 1));
    prec_arr = prec_arr1 = np.zeros((nbOfUsers, 1));
    rec_arr = rec_arr1 = np.zeros((nbOfUsers, 1));
    acc_arr = acc_arr1 = np.zeros((nbOfUsers, 1));
    f1sr_arr = f1sr_arr1 = np.zeros((nbOfUsers, 1));
    conf_mat = []
    pref_mat = []
    for userIdx in range(0, nbOfUsers):
        gt_indicator = np.array(user_score[:, userIdx])
        gt_ind = np.clip(gt_indicator, 0, 1)
        gt_ind = (gt_indicator > 0).astype(int)
        conf_mat = metrics.confusion_matrix(gt_ind,sum_ind)
        pref_mat = metrics.precision_recall_fscore_support(gt_ind, sum_ind,average=None)
        acc_mat = metrics.accuracy_score(gt_ind,sum_ind)

        matches = (gt_ind==sum_ind)
        n_tp_matches = [True if sum_ind[id] == 1 and sum_ind[id] == gt_ind[id] else False for id in range(vect_len)]
        n_tp = n_tp_matches.count(True)
        n_fp_matches = [True if sum_ind[id] == 1 and gt_ind[id] == 0 else False for id in
                        range(vect_len)]  # (gt_ind == 0 and sum_ind == 1)
        n_fp = n_fp_matches.count(True)
        n_fn_matches = [True if sum_ind[id] == 0 and gt_ind[id] == 1 else False for id in
                        range(vect_len)]  # (gt_ind == 1 and sum_ind == 0)
        n_fn = n_fn_matches.count(True)
        n_tn_matches = [True if sum_ind[id] == 0 and sum_ind[id] == gt_ind[id] else False for id in range(vect_len)]
        n_tn = n_tn_matches.count(True)
        acc = prec = rec = f1_scr = 0
        if n_tp + n_tn > 0:
            acc = (n_tp + n_tn)/ (n_tp + n_tn + n_fp + n_fn)
        if n_tp + n_fp > 0:
            prec = n_tp / (n_tp + n_fp)
        if n_fp + n_fn > 0:
            rec = n_tp / (n_tp + n_fn)
        if prec + rec > 0:
            f1_scr = 2 * prec * rec / (prec + rec)
        acc_arr[userIdx] = acc
        prec_arr[userIdx] = prec
        rec_arr[userIdx] = rec
        f1sr_arr[userIdx] = f1_scr
        user_acc[userIdx] = np.mean(matches)
        acc_arr1[userIdx] = acc_mat#[1][0]
        prec_arr1[userIdx] = pref_mat[0][1]
        rec_arr1[userIdx] = pref_mat[1][1]
        f1sr_arr1[userIdx] = pref_mat[2][1]
    ground = (ground_score>=0.5).astype(int)
    ground_matches = (ground==sum_ind)
    ground_acc = np.mean(ground_matches)
    gacc = metrics.accuracy_score(ground, sum_ind)
    print("Ground Accuracy: ", gacc)
    print(f"TP:{n_tp},FP:{n_fp},FN:{n_fn},TN:{n_tn},Prec:{pref_mat[0][1]},Recl:{pref_mat[1][1]},F1Sr:{pref_mat[2][1]}")
    print(f"TP:{n_tp},FP:{n_fp},FN:{n_fn},TN:{n_tn},Acc:{np.max(acc_arr)},Prec:{np.max(prec_arr)},Recl:{np.max(rec_arr)},F1Sr:{np.max(f1sr_arr)}")

    return user_acc,np.max(acc_arr),ground_acc,np.mean(f1sr_arr),np.max(f1sr_arr)

if __name__ == '__main__':
    # nthrds = multiprocessing.cpu_count()
    # os.environ['NUMBA_NUM_THREADS'] = str(nthrds)
    #
    # nthrds = nb.get_num_threads()
    # print(nthrds)
    # nb.set_num_threads(nthrds)
    #
    # inp_fldr = 'D:/Projects/DataSets/SumMe/videos/'
    # inp_fldr = 'D:\\Project\\Datasets\\tvsumm'
    inp_fldr = inp_fldr.replace('\\', '/')
    op_fldr = os.path.join(inp_fldr,'output_l2')
    # lst_vid_files = os.listdir(inp_fldr)
    # lst_mp4_files = lst_vid_files
    lst_mp4_files = glob.glob(f'{inp_fldr}/*.mp4')#(f'{directory}/*.txt')
    writer.writerow(["VideoName", "FrameCount", "MissCount", "Accuracy", "GTAcc", "MnF1Score", "MxF1Score","Time"])
    algo = 6

    # lst_mp4_files = lst_mp4_files[18:]
    for vid_file in lst_mp4_files:
      # inp_pth = os.path.join(inp_fldr,inp_vid)
      print(vid_file)
    # print("Folders\n",inp_fldr,opt_fldr)
      inp_file = os.path.basename(vid_file)
      print(inp_file)
    # print("Input Path\n",inp_pth)
    # print("Output Path\n",opt_pth)
      vid_nm = inp_file.split('.')[0]
      # Load GroundTruth file
      gt_file = GTPATH + '/' + vid_nm + '.mat'
      gt_data = scio.loadmat(gt_file)

      user_score=gt_data.get('user_score')
      ground_data=gt_data.get('gt_score')
      nFrames = user_score.shape[0]
      # nFPS = gt_data.get('FPS')
      nFPS = int(gt_data.get('FPS')[0][0])
      # nbOfUsers = user_score.shape[1]
      start_time = datetime.now()
      # print("StartTime",start_time)
      # ms_frame_cnt, frms_lst, prcsd_lst, op_pth,summary_vect, min_thrsh, max_thrsh = video_to_frames(vid_file,op_fldr, int(algo))
      ms_frame_cnt = video_to_frames(vid_file,op_fldr, int(algo))

      # evaluate_summary(summary_vect,vid_nm,gt_data)
      end_time = datetime.now()
      # ssim_lite.parallel_diagnostics(level=4)
      # print("EndTime",end_time)
      # print("Total frame count",frame_cnt)
      # plot_adpt_thrs(vid_nm)
      process_time = end_time-start_time
      # print("processing time:",process_time)
      acc_arry, accuracy, grnd_trt_acc,mean_fone_score, max_fone_score = evaluate_summary(summ_vect, user_score,ground_data)
      record_log_data(csv_path,vid_nm, nFrames, ms_frame_cnt, acc_arry,accuracy, grnd_trt_acc, mean_fone_score, max_fone_score, process_time)
      print(vid_nm,accuracy,"GTACC",grnd_trt_acc)
      summ_vect.clear()
      adapt_thrs_ar_x.clear()
      adapt_thrs_arry.clear()
    file.close()